# Generated by Django 3.2.4 on 2023-06-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email_distribution_list',
            new_name='EmailDistributionList',
        ),
    ]
