# Generated by Django 3.2.4 on 2023-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('qty_small', models.IntegerField(default=0)),
                ('qty_medium', models.IntegerField(default=0)),
                ('qty_large', models.IntegerField(default=0)),
                ('qty_extra_large', models.IntegerField(default=0)),
            ],
        ),
    ]
