# Generated by Django 3.2.4 on 2023-03-12 19:58

import apps.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image1',
            field=models.ImageField(storage=apps.items.models.ItemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='image2',
            field=models.ImageField(storage=apps.items.models.ItemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='image3',
            field=models.ImageField(storage=apps.items.models.ItemStorage(), upload_to=''),
        ),
    ]
