# Generated by Django 3.2.4 on 2023-03-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20230312_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
    ]
