# Generated by Django 3.2.4 on 2023-05-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20230312_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='label',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='sale',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
