# Generated by Django 3.2.4 on 2023-05-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20230516_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='sale',
            field=models.IntegerField(default=0),
        ),
    ]
