# Generated by Django 5.0.3 on 2024-03-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='featured_checked',
            field=models.BooleanField(default=False),
        ),
    ]
